import Head from 'next/head';
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from '../lib/query';

export default function Home() {
  //fetching data from strapi backend

  const [productsResults] = useQuery({query: PRODUCT_QUERY});
  const {data, fetching, error} = productsResults;

  console.table(data);

  return  (
    <div >
      <Head>
        <title>KiCKS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Next</h1>
      </main>
    </div>
  )
}
