import Head from 'next/head';
import { useQuery } from 'urql';
import { PRODUCT_QUERY, HOME_ASSETS_QUERY } from '../lib/query';
import {Hero} from '../containers'
import {Layout} from '../layout';

export default function Home() {
  //fetching data from strapi backend

  const [assetsResults] = useQuery({query: HOME_ASSETS_QUERY});
  const {data, fetching, error} = assetsResults;

  // const homeAssets = data.assets.data.filter(asset => asset.attributes.Location === 'Home');

  // console.log(homeAssets[0].attributes.Image.data[0].attributes)

  console.log(data)

  return  (
      // <div style={{backgroundColor: 'black'}}>
      //   {/* <Head>
      //     <title>KiCKS</title>
      //     <meta name="description" content="Generated by create next app" />
      //     <link rel="icon" href="/favicon.ico" />
      //   </Head> */}
        
      //   <Nav color="white"/>

      //   <main>
      //     {/* <Hero heroAsset={homeAssets[0].attributes.Image.data[0].attributes}/> */}
      //     <Hero />
      //   </main>
      // </div>

      
      // <>
      //   <Hero/>
      //   <h1>HI</h1>
      // </>
      <Layout color="white">
        <Hero/>
      </Layout>
  )
}
