import Head from 'next/head';
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from '../lib/query';
import { Nav } from '../layout';


export default function Home() {
  //fetching data from strapi backend

  const [productsResults] = useQuery({query: PRODUCT_QUERY});
  const {data, fetching, error} = productsResults;

  return  (
      <div style={{backgroundColor: 'black'}}>
        <Head>
          <title>KiCKS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Nav color="white"/>
        </main>
      </div>
  )
}
