import Head from 'next/head';

const Head = () => {
  return (
    <>
        <Head>
          <title>KiCKS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    </>
  )
}

export default Head;